#!/bin/bash

# At the moment, this installs and runs openfire, however, I can't connect to
# it.  I believe I need to tell it to use mysql, somehow.
wget http://download.igniterealtime.org/openfire/openfire_3_9_3.tar.gz
tar -xvzf openfire_3_*.tar.gz
rm openfire_3_*.tar.gz
sudo mv openfire /opt/
sudo ln -s /opt/openfire/bin/openfire /etc/init.d/
service openfire start

# # Copy the files that openfire would generate diffs for in its manual installation.
# (
#   cd openfire_files_after_setup
#   for file in `find . -type f`; do
#     cp -a $file /opt/openfire/$file
#   done
# )

