#!/bin/bash

# ----------------------------------------------------------------------------
# openjdk
#
sudo apt-get install openjdk-7-jdk -y
sudo apt-get install openjdk-7-jre -y

# ----------------------------------------------------------------------------
# junit4
#
sudo apt-get install junit4 -y
