#!/bin/bash

(
  cd `dirname $0`
  rm -f install.log
  touch install.log
  date >> install.log
  for filename in `find . -name "install_*" | sort`; do
    ./$filename 2>&1 | tee -a install.log
  done
)
