#!/bin/bash

wget http://download.igniterealtime.org/openfire/openfire_3_9_3.tar.gz
tar -xvzf openfire_3_*.tar.gz
rm openfire_3_*.tar.gz
sudo mv openfire /opt/
sudo ln -s /opt/openfire/bin/openfire /etc/init.d/
service openfire start

# This adds openfire to the rc directories so it will automatically start
# when the machine is rebooted
sudo update-rc.d openfire defaults
